trailingComma: 'none'
useTabs: true
tabWidth: 4
semi: true
singleQuote: true
printWidth: 100
endOfLine: 'crlf'
overrides:
  - files:
      - '*.json'
      - '*.yaml'
      - '*.yml'
    options:
      tabWidth: 2
      useTabs: false
